### ISSUE TITLE
What are the benefits of this fork?

### ISSUE THREAD

**Issue by lextm** [ArchaicOokami/DockPanel#1]
I am one of the current maintainers of DPS at https://github.com/dockpanelsuite/dockpanelsuite. We evaluate forks periodically to see what patches we might merge to the upstream.

Can you describe the greatest features of your fork? Meanwhile, it is not a standard fork we see at GitHub (as you don't fork from our repo, and simply start from a random DPS source drop).

**Comment by ArchaicOokami** [comment]
This mostly I maintain for myself but I have just simply been attempting to clean it up here and there if/when it seems to run slow.. as well I tried to eliminate the need for the "themes" system by putting in properties to change the colors of all the dock aspects from Designer view and I also attempted to make it run on linux - that didnt work out so well so ive started focusing on doing OpenGL stuff and soon to make my own form of DockPanels from that (AKA I wont be maintaining this repo soon and most likely taking it down)

**Comment by ArchaicOokami** [comment]
All in all you probably wont want any changes I have made in this -> as they are an attempt to do things entirely differently than DockPanelSuite was concerned with.. lots of stuff removed.

**Comment by lextm** [comment]
Thanks. This information is very useful.
